-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'TASK_DELETED';
ALTER TYPE "NotificationType" ADD VALUE 'TASK_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'COMMENT_DELETED';
ALTER TYPE "NotificationType" ADD VALUE 'PROJECT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'PROJECT_DELETED';
